-- Copy and paste this into Supabase SQL Editor
create table if not exists users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  is_admin boolean default false,
  is_approved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Optional: Enable RLS
alter table users enable row level security;
create policy "Allow all access for demo" on users for all using (true) with check (true);
